# Generated by Django 5.0.1 on 2024-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_payment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
