# Generated by Django 5.0.1 on 2024-12-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0010_alter_userpet_gender_alter_userpet_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpet',
            name='price',
        ),
    ]
