# Generated by Django 5.0.1 on 2024-12-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0012_petinsurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinsurance',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petinsurance',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
