# Generated by Django 5.0.1 on 2024-12-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0014_alter_petinsurance_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopt_date', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_pets', to='petapp.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.adopt')),
            ],
        ),
    ]
